### ISSUE TITLE
Issue w/ Encoding

### ISSUE THREAD

**Issue by mclim9** [AndreMiras/coveralls-python-action#12]
Sorry if this is not the right forum.  Please delete if inappropriate.

I am using 'future_fstrings' library. so that Python 2.7 can use 3.8 f strings.  Library is pip installed during tests, but errors when running coveralls-python-action.  Is there provision to add encoding  to coveralls-python-action?  Alternatively, maybe install requirements.txt?

Error message in github actions:
> Trying submitting coverage with service_name: github...
> cd .
> cd /github/workspace
> unknown encoding: future_fstrings
> Traceback (most recent call last):
>   File "/usr/local/lib/python3.8/site-packages/coveralls/reporter.py", line 108, in report
>     from coverage.report import Reporter  # pylint: disable=import-outside-toplevel
> ImportError: cannot import name 'Reporter' from 'coverage.report' (/usr/local/lib/python3.8/site-packages/coverage/report.py)
> 
> During handling of the above exception, another exception occurred:

**Comment by AndreMiras** [comment]
Thanks for the report.
This is because the `coveralls` pip package you have is outdated. You're probably running on `coveralls==1.11.1` while you should be on `coveralls==2.2.0`. And this is happening because coveralls2 doesn't support Python 2.7.
So this is something upstream in https://github.com/coveralls-clients/coveralls-python
But I would advise you to migrate to Python3
